### ISSUE TITLE
Maybe add a link to Bitcoin whitepaper?

### ISSUE THREAD

**Issue by danger89** [zquestz/bitcoincash#105]
Below the "The History of Bitcoin Cash" heading you are referring to the whitepaper, but maybe host the file and link to the document?

**Comment by zquestz** [comment]
We should link to it, it is on the server already. https://bitcoincash.org/bitcoin.pdf

**Comment by danger89** [comment]
Ah definitely. It's whitepaper day after all 😜

**Comment by danger89** [comment]
PR created.
