### ISSUE TITLE
Remove smartBCH

### ISSUE THREAD

**Issue by melroy89** [zquestz/bitcoincash#107]
SmartBCH is too bad closed. The bridge is closed (between BCH mainnet and smartBCH sidechain). Maybe it's a good idea to remove it from the site..?

**Comment by zquestz** [comment]
Right now the bridge is closed, you might be right. We should probably remove it until there is a decentralized bridge.

**Comment by danger89** [comment]
I talked with Dustin and some others from smartBCH community. Here a quote from that conversation:


> The bridge was centralized.  There are currently only dexes (some of which are multichain and allow direct smartBCH<->mainchain BCH exchange at AMM rates), but no 1:1 backing.  The restructuring that CoinFlex is trying to get approved at Seychelles court combined with a mostly silent group "representing smartBCH" would allegedly provide 1:1 backing, but still no direct exchange 1:1 bridge until shagate is complete.
> Given those circumstances, it seems reasonable to me to remove the listing until 1:1 guaranteed exchange with provable on-chain backing is reinstated.

**Comment by zquestz** [comment]
I agree, we can remove until a real bridge is available.

**Comment by danger89** [comment]
Another person mentioned however:

> I think anything you want to proceed with needs to have a nice thought behind. Please proceed with caution.
> Never forget this community is not new, people have built and we're still fighting for getting the chain back on its feet.
> I'd rather don't rush to delete all sBCH related stuff if only as a sign of respect for this community.
> 
> Not saying you don't care btw, I know you do. Just think that through a bit more and see if it even makes any good.

I propose to give them a change to update the smartbch.org website for now, with a warning on their site. If that is not done within a couple of weeks, we can still decide to remove it.

**Comment by zquestz** [comment]
Seems reasonable.

**Comment by zquestz** [comment]
I went ahead and removed all broken links.

**Comment by melroy89** [comment]
Great. should I close it? I don't think you gonna remove SmartBCH. But I will never touch smartBCH myself personally.

**Comment by zquestz** [comment]
Yeah I am very likely to remove it soon. I want to create the CashTokens bridge first, so people can move over their value. Then we can burn it with fire.
