### ISSUE TITLE
Introducing a forum

### ISSUE THREAD

**Issue by melroy89** [zquestz/bitcoincash#114]
We might want to introduce a forum on [bitcoincash.org](https://bitcoincash.org) site to bring the community together. Especially since bitcointalk.org, /r/Bitcoin as well as Bitcoin StackExchange are not welcoming the BCH (big blocks) community.

**Proposal sub-domain:** forum.bitcoincash.org

This would require an additional Kubernetes deployment ideally. Depending on where you host the infrastructure/Kubernetes cluster, I can help you here as well. The current site is just static content, which is very low in resources, a forum might require a bit more resources.

[SMF](https://simplemachines.org/) is used originally on bitcoin.org/smf which is now bitcointalk.org. However, we are of course free to use whatever software we might want to use. Since I think there are much better alternative like Discourse for example.

I believe a dedicated forum for our community would really empower the community.

**Comment by zquestz** [comment]
I am definitely down to have a forum, but someone would need to pick up this work.
