### ISSUE TITLE
Add functionality to Buy BCH

### ISSUE THREAD

**Issue by notrigs** [zquestz/bitcoincash#122]
Hello there,

Its my formal request to add a functionality to buy BCH on bitcoincash.org.

Ultimately it will make the website more useful by offering users to buy BCH directly in their custodial or non custodial wallet. 

To make it easier, we have aggregated all major fiat to crypto onramps in one widget. Please check out the widget here: https://widget.onramper.com/?onlyCryptos=BCH

Fees on this widget can be easily compared and it does not cost more than reaching them directly. Some onramps are even cheaper such as Moonpay, coinify, mercuryo, etc.

If requested, it is possible to add affiliate commission on these purchases to be given towards maintaining this website.

Please let me know if I can help with anything regarding this.

Regards,
Rigved Bhatt
Account Executive, Onramper

**Comment by zquestz** [comment]
We will not be adding purchasing to this site, it is for information only. Exchanges can do the selling. =--)
