### ISSUE TITLE
Cleanup dead wallets from the main page

### ISSUE THREAD

**Issue by mahnunchik** [zquestz/bitcoincash#127]
While I was adding a new wallet, I noticed that there are dead wallets. I think they may be removed from the list to not confuse users.

If you wish I may prepare a PR.

## Pokket

Website is down: https://pocket.cash/
No app in the Play Store.

## Jaxx

Information on the website:

> We've announced plans to retire Jaxx Liberty on March 27, 2023

# StrongCoin

Website is down: https://strongcoin.com/
No apps in stores.

**Comment by zquestz** [comment]
Absolutely do a PR, would be happy to fix this!
