### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PedroR82** [zquestz/bitcoincash#13]
Hello there.

How is the localization effort going?
I was told there will be a solution in order to include other languages on this page. I'm willing to do the translation into Spanish. 

I actually already forked and translated the project, but there have been some changes after that and I guess my approach was not the best possible solution for localization. 

https://github.com/PedroR82/website/tree/Spanish 

Please let me know if there's a new way for me to collaborate on the translation now.

Thanks.

**Comment by zquestz** [comment]
Localization support is still incoming. There will be a .yaml file soon that will be provided to translators. Sorry for the wait.

**Comment by zquestz** [comment]
Just a heads up, localization support is now available with docs in the README. All PR's for updates should go to https://github.com/bitcoincashorg/website.
