### ISSUE TITLE
nginx not found

### ISSUE THREAD

**Issue by Gargo** [zquestz/bitcoincash#32]
installed docker and tried to run according with your instructions on windows 10. The same in OS X
Could you please add info how to install/configure this nginx?

```
Sending build context to Docker daemon  83.12MB
Step 1/3 : FROM nginx
latest: Pulling from library/nginx
e7bb522d92ff: Pull complete 
6edc05228666: Pull complete 
cd866a17e81f: Pull complete 
Digest: sha256:cf8d5726fc897486a4f628d3b93483e3f391a76ea4897de0500ef1f9abcd69a1
Status: Downloaded newer image for nginx:latest
 ---> 3f8a4339aadd
Step 2/3 : COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder798445969/nginx.conf: no such file or directory
```

**Comment by zquestz** [comment]
This was just updated recently. Basically now there is a precompile step for translations. You will need to run `rake translations:build` or `rake` which will build the translations, then generate the docker image. I will update the docs!
