### ISSUE TITLE
Adding bit2c.co.il to the list of exchanges that support Bitcoin Cash

### ISSUE THREAD

**Issue by avinoamOltchik** [zquestz/bitcoincash#38]
Hey,

My name is Avinoam and I'm from the bit2c.co.il team.

We are a cryptocurrency exchange that enables trade with Bitcoin since March 2013.

Our platform currently supports trade with Bitcoin Cash and we would like to appear on the listing of exchanges on your website.

Our logo can be obtained [here](https://bit2c.co.il/Content/img/bit22.png).

I'm available to provide any information about our service and company that may be needed.

My email address is avinoam@bit2c.co.il

I hope this would be right place to place this request. If i'm mistaken please be kind and let me know where I should add this request.

Thanks!

Avinoam Oltchik
Bit2c.co.il Team

**Comment by zquestz** [comment]
The best place for this is https://github.com/bitcoincashorg/website. This is just my personal working copy.
