### ISSUE TITLE
BCHForum.org  - Bitcoin Cash Forum

### ISSUE THREAD

**Issue by miranos** [zquestz/bitcoincash#43]
Welcome to Bitcoin Cash Forum

From here: https://bchforum.org

**Comment by jeffreyrufino** [comment]
Thanks I'm like the first user.

**Comment by miranos** [comment]
Welcome :D

**Comment by jeffreyrufino** [comment]
There's something wrong with uploading profile pictures..60*60 and under
2kb.

It says to contact the admin.

**Comment by miranos** [comment]
You can do it now :)

Thank's for the alert.

**Comment by jeffreyrufino** [comment]
Cool, let's promote this now :)

*Jeffrey Rufino*





Jeffrey Rufino

*Digital Marketing Manager*

m: 0411 530 910
a: Unit 3 172-180 Mayer St, Cairns, 4870
w: www.localvisibility.com.au/  e: jeff@localvisibility.com.au

Let's Chat - Book A Time <http://calendly.com/jeffreyrufino>
