### ISSUE TITLE
Update included applications in general

### ISSUE THREAD

**Issue by RowanSkie** [zquestz/bitcoincash#45]
Out of all Bitcoin Cash-based websites, bitcoincash.org still uses the orange font when most of the ecosystem has used the green BCH logo.

EDIT: Also noticed this one still uses the old Flowee logo.
EDIT 2: A lot of the exchanges still have the old logos as well.
EDIT 3: Maybe we really just need upgrades on all of it...

**Comment by zquestz** [comment]
We need all the updates. For now I fixed the Flowee and BU logos. Could use help for more. =)

**Comment by zquestz** [comment]
Literally all these issues have been fixed.

- We are green
- Logos and links are now up to date
