### ISSUE TITLE
Broken Menu (Community) when using Brazilian Portuguese version

### ISSUE THREAD

**Issue by Ralphive** [zquestz/bitcoincash#46]
![image](https://user-images.githubusercontent.com/9930965/110256695-29e8af80-7f92-11eb-9fb9-1bfce1606082.png)

**Comment by zquestz** [comment]
Looks fine on my end... Can you try clearing your cache?

<img width="1469" alt="Screen Shot 2021-03-09 at 11 38 55 AM" src="https://user-images.githubusercontent.com/83898/110541637-1d687200-80cc-11eb-9162-ead0800b6f33.png">

**Comment by zquestz** [comment]
NM I see the issue now. WIll try to prep a fix. =)

**Comment by zquestz** [comment]
Fixed!
