### ISSUE TITLE
Make bitcoincashresearch the go-to for change proposal discussion, not bitcoin-ml mailing list

### ISSUE THREAD

**Issue by ftrader** [zquestz/bitcoincash#56]
It caught my eye since it's on the front page.

The mailing list is hardly ever used anymore, the last message in the archive is from someone annoyed asking how the list got his mailing address.

We should change it to direct people to bitcoincashresearch.org instead.

If I have the time, I'll try to put in a PR tomorrow.

Otherwise, sooner we get rid of the bitcoin-ml reference, the better...

**Comment by zquestz** [comment]
Looking forward to the PR!

**Comment by zquestz** [comment]
Fixed. Will deploy soon.
