### ISSUE TITLE
Several Languages missing translation for graphics

### ISSUE THREAD

**Issue by Ralphive** [zquestz/bitcoincash#60]
The [Graphics](https://bitcoincash.org/graphics/) misses translation for several languages. Therefore, it doens't even show up in the menu when one of them is activated.

I suggest leave the option in the menu to an English version while they are not translated.

The missing ones are:
- ms
- pt-br
- pt-pt
- id
- nl
- vi
- tr
- cs
- el
- ru
- hi
- ja
- zh-cn
- zh-tw
- sk
- ko

Example in French:
![image](https://user-images.githubusercontent.com/9930965/112039739-47924900-8b3c-11eb-8ab3-234c376634e1.png)

Same menu in English
![image](https://user-images.githubusercontent.com/9930965/112039786-5547ce80-8b3c-11eb-87f4-bb6a08f6ae10.png)

**Comment by zquestz** [comment]
We have been getting them translated! We now have Simplified Chinese, Spanish, Filipino, German, Polish and Italian fully translated! You can help contribute at https://crowdin.com/project/bitcoin-cash

**Comment by Ralphive** [comment]
Thanks, I did review the Pt-br files on crowdin and a lot of the graphics text was already translated. Should I create a PR with the content extracted from Crowdin (This process should also be in the README) happy to do it, once clarified :)

**Comment by zquestz** [comment]
@Ralphive just make sure to +1 any translations you see that are correct! The ones there are from a machine learning based auto translation system and need human review! Once we have reviewed all the translations then I can post them on the site!

**Comment by Ralphive** [comment]
got it, so no need for PR, will do all on the crowdin. Thanks

**Comment by Ralphive** [comment]
Finish +1 the good one. Just notice the the string affected by #62 is on crowdin as well. Heads up, so the links for the old mailing list are not back once translations are completed. I fixed for PTbr, but others might not be so cautious.

**Comment by zquestz** [comment]
This has made a ton of progress. Closing. 😀
