### ISSUE TITLE
[Enhancement] Flyers for merchants onboarding

### ISSUE THREAD

**Issue by Ralphive** [zquestz/bitcoincash#61]
Just want to raise the discussion.

I ran across these and found the job pretty neat.
It didn't get much [traction on Reddit](https://www.reddit.com/r/btc/comments/lu546p/new_and_improved_flyer_for_merchants/). So I wonder if there would be a place for them in the graphics page. 

Thoughts?

![image](https://user-images.githubusercontent.com/9930965/112666393-0c518c00-8e54-11eb-953b-cafc43683e2d.png)

**Comment by zquestz** [comment]
YES! There is definitely room on the graphics page for high quality promotional material! I also would love to see this available in different languages! We can obviously start with just english, but I think this could be very useful in other places.

**Comment by zquestz** [comment]
Closing, feel free to put up a PR for the graphics page if you still are interested in contributing.
