### ISSUE TITLE
Showcase Bitvavo on your website

### ISSUE THREAD

**Issue by noahpierau** [zquestz/bitcoincash#71]
Dear bitcoincash.org team,

This issue was created on behalf of Bitvavo, one of the biggest regulated EUR exchanges in Europe. Bitvavo is proudly based in Amsterdam and has been offering the BCH/EUR trading pair for some time now.
 
On your website we saw the page https://bitcoincash.org/ where you showcase some available exchange options for BCH. We were wondering: can you add Bitvavo to this list?
 
It will be beneficial for you to showcase Bitvavo on your website, since it is one of the largest regulated exchanges in Europe and committed to support Bitcoin Cash. We also provide a custom asset page: https://bitvavo.com/en/bitcoin-cash (you can link to local versions of the website if you replace "EN" with DE, ES, FR, IT or NL).

Currently we are launching a new website with a redesigned logo. If you are willing to showcase Bitvavo, kindly send us the required logo dimensions and file format (png, jpg, svg) for your website, so our designers can create this for you.

Best regards,

https://bitvavo.com/en
Bitvavo B.V.
Herengracht 450
1017 CA Amsterdam
The Netherlands

**Comment by zquestz** [comment]
We just require a logo that is on white, no taller than 80px, in png format.

**Comment by noahpierau** [comment]
Dear @zquestz,  

Attached you will find the Bitvavo logo in the required size and file format:

![bitvavo-bch](https://user-images.githubusercontent.com/16287891/135405053-7fff45aa-7bc8-4247-bda8-ec3600a3b4be.png)

We recommend to link to the custom BCH page: https://bitvavo.com/en/bitcoin-cash (for localized versions, just replace "en" with "de", "es", "fr", "it" or "nl" in the link), but linking to https://bitvavo.com is possible as well.

**Comment by noahpierau** [comment]
Should we open a new issue, since this one has been closed already? 🤔

**Comment by zquestz** [comment]
I am happy to add it, can you just put up a PR with the changes? Then I can merge and get that posted for you. =)

**Comment by noahpierau** [comment]
Thank you for your help, a PR was created: https://github.com/zquestz/bitcoincash/pull/80
