### ISSUE TITLE
SLP Token Wallets

### ISSUE THREAD

**Issue by Ekliptor** [zquestz/bitcoincash#74]
Can we mark all wallets that support SLP tokens with a SLP Icon/Tag on your website?

I receive more requests for "how to pay in my own token" these days at Prompt.Cash and information about SLP wallet support is unfortunately scarce.

Also some wallets might only support specific hard-coded SLP tokens, while others support all. So maybe 2 different tags would be appropriate.

**Comment by zquestz** [comment]
Would absolutely accept a PR to add those badges. Could use some more community involvement on making changes. =)

**Comment by zquestz** [comment]
Closing, if someone wants to tag SLP wallets they can, but this is no longer a priority.
