### ISSUE TITLE
How can I review code of the bitcoin cash protocol?

### ISSUE THREAD

**Issue by MasterMintZ** [zquestz/bitcoincash#76]
How can I review code of the bitcoin cash protocol? Id like to study the code to possibly work on the project in the future if you need help.

**Comment by zquestz** [comment]
There are a number of full node projects. Here are a couple to get you started.

https://bitcoincashnode.org
https://bchd.cash

**Comment by zquestz** [comment]
There are also good threads at bitcoincashresearch.org
