### ISSUE TITLE
Pin BCH repo? And create an organisation?

### ISSUE THREAD

**Issue by danger89** [zquestz/bitcoincash#78]
Maybe you should pin this repo on your profile:

https://github.com/zquestz

That being said. Maybe it looks more professional if you [create the official bitcoincash repo](https://github.com/settings/organizations) under a organisation rather than your personal account?...

For example, something like:
https://github.com/bitcoin-cash

Looks more trusted.

Regards,
Melroy

**Comment by zquestz** [comment]
I think creating an org makes sense. The old org was owned by Bitcoin ABC.

One thing to note, there is no official bitcoin cash site, they are ALL unofficial. Even though this is hosted at bitcoincash.org it doesn't make it any more official than other BCH sites.

I don't really want to create or manage a bitcoin-cash org on github, happy to move the code there if the community sets it up.
