### ISSUE TITLE
Add TangoSwap and SmartSwap

### ISSUE THREAD

**Issue by ianblas** [zquestz/bitcoincash#89]
Hi, can you add TangoSwap and SmartSwap has exchanges too? 

Links:
https://tangoswap.cash/
https://smartswap.fi/

Icons:

TangoSwap: https://drive.google.com/file/d/16DlJJj4VMxj2LNDTKLorVr5CGfpHiDm5/view?usp=drivesdk

SmartSwap: https://drive.google.com/file/d/1EiKprXhjMEfKwPgxgJcrOg1AQkQSqjTk/view?usp=drivesdk

Thanks

**Comment by zquestz** [comment]
Just send over a PR, I will happily add them. That way you can make sure your logo looks excellent. =)
