### ISSUE TITLE
Adding Wallet to bitcoincash.org

### ISSUE THREAD

**Issue by satoshiWallet** [zquestz/bitcoincash#9]
Hello,

Great work on the bitcoincash.org website!

Satoshi Wallet is a new Bitcoin Cash wallet, and we would like to ask if it can be added to the new bitcoincash.org website?  We made a post about Satoshi Wallet on /r/btc and /r/bitcoincash today.  This is a link to the /r/btc post: https://www.reddit.com/r/btc/comments/72cjiv/new_satoshi_bitcoin_cash_wallet_for_ios_android/

https://satoshi.dance

Also, if asking about this on github is not the correct place, please let us know how to properly  make the request.  I read in the /r/btc post that we should make requests through the github link on the website.

**Comment by zquestz** [comment]
This is almost the right place! This is my personal repo. All official requests should be at https://github.com/bitcoincashorg/website!

**Comment by satoshiWallet** [comment]
Hi, sorry but I am new to posting on github.  Do you know how I can send the request to the correct place?  When I go to the website repository, I click "New Pull Request", and it brings me to your personal github repository for some reason. Is there another place where I should be making the request?
