### ISSUE TITLE
Placement on the “EXCHANGES” section

### ISSUE THREAD

**Issue by MariaSwapzone** [zquestz/bitcoincash#96]
Hello!

I am Maria, a marketing manager at Swapzone - a cryptocurrency exchange aggregator. We'd like to become an official exchange of your website https://bitcoincash.org/ and be featured on the “EXCHANGES” section. Could you please tell me on what terms you are ready to insert us?

Looking forward to your reply!

Best regards, Maria

**Comment by zquestz** [comment]
Done. =)
